CREATE DATABASE IF NOT EXISTS DTSPROJECT;
USE DTSPROJECT;

CREATE TABLE IF NOT EXISTS CUSTOMER (
    CustomerID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Phone VARCHAR(20),
    Email VARCHAR(150) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS STAFF (
    StaffID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Role VARCHAR(50) NOT NULL,
    Email VARCHAR(150) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS EVENT (
    EventID INT AUTO_INCREMENT PRIMARY KEY,
    EventName VARCHAR(100) NOT NULL,
    EventType VARCHAR(50),
    EventDate DATE,
    EventTime TIME,
    VenueName VARCHAR(100),
    Address VARCHAR(255),
    GuestCount INT CHECK (GuestCount >= 0),
    CustomerID INT NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS MENU_ITEM (
    MenuItemID INT AUTO_INCREMENT PRIMARY KEY,
    ItemName VARCHAR(100) NOT NULL,
    Price DECIMAL(10,2) CHECK (Price >= 0),
    StaffID INT NOT NULL,
    FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS ORDERS (
    OrderID INT AUTO_INCREMENT PRIMARY KEY,
    OrderStatus VARCHAR(50),
    IsSelected BOOLEAN,
    EventID INT NOT NULL,
    StaffID INT NOT NULL,
    FOREIGN KEY (EventID) REFERENCES EVENT(EventID) ON DELETE RESTRICT,
    FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS ORDER_MENU_ITEM (
    OrderID INT,
    MenuItemID INT,
    Quantity INT CHECK (Quantity > 0),
    PriceAtOrderTime DECIMAL(10,2) CHECK (PriceAtOrderTime >= 0),
    PRIMARY KEY (OrderID, MenuItemID),
    FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID) ON DELETE CASCADE,
    FOREIGN KEY (MenuItemID) REFERENCES MENU_ITEM(MenuItemID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS INVOICE (
    InvoiceID INT AUTO_INCREMENT PRIMARY KEY,
    InvoiceNumber VARCHAR(50) UNIQUE NOT NULL,
    InvoiceDate DATE,
    Subtotal DECIMAL(10,2) CHECK (Subtotal >= 0),
    ServiceCharge DECIMAL(10,2) CHECK (ServiceCharge >= 0),
    Status VARCHAR(50),
    OrderID INT NOT NULL,
    PreviousInvoiceID INT NULL,
    StaffID INT NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID) ON DELETE RESTRICT,
    FOREIGN KEY (PreviousInvoiceID) REFERENCES INVOICE(InvoiceID) ON DELETE SET NULL,
    FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS PAYMENT (
    PaymentID INT AUTO_INCREMENT PRIMARY KEY,
    PaymentDate DATE,
    Amount DECIMAL(10,2) CHECK (Amount > 0),
    InvoiceID INT NOT NULL,
    FOREIGN KEY (InvoiceID) REFERENCES INVOICE(InvoiceID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS APPROVAL (
    ApprovalID INT AUTO_INCREMENT PRIMARY KEY,
    Status VARCHAR(50),
    ApprovalDate DATE,
    InvoiceID INT NOT NULL,
    CustomerID INT NULL,
    StaffID INT NULL,
    FOREIGN KEY (InvoiceID) REFERENCES INVOICE(InvoiceID) ON DELETE RESTRICT,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID) ON DELETE SET NULL,
    FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID) ON DELETE SET NULL
);
